---
title: "10-read-in"
output: html_notebook
---

Import libraries.
```{r}
library(readxl)
library(tidyverse)
library(janitor)
library(ggplot2)
library(tidytext)
library(wordcloud2)
library(RColorBrewer)

```

Read in raw data and make the column names.
```{r}
df_2000 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2000")
names(df_2000) <- df_2000[1,]
df_2000 <- df_2000[-1,]

df_2001 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2001")
names(df_2001) <- df_2001[1,]
df_2001 <- df_2001[-1,]

df_2002 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2002")
names(df_2002) <- df_2002[1,]
df_2002 <- df_2002[-1,]

df_2003 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2003")
names(df_2003) <- df_2003[1,]
df_2003 <- df_2003[-1,]

df_2004 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2004")
names(df_2004) <- df_2004[1,]
df_2004 <- df_2004[-1,]

df_2005 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2005")
names(df_2005) <- df_2005[1,]
df_2005 <- df_2005[-1,]

df_2006 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2006")
names(df_2006) <- df_2006[1,]
df_2006 <- df_2006[-1,]

df_2007 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2007")
names(df_2007) <- df_2007[1,]
df_2007 <- df_2007[-1,]

df_2008 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2008")
names(df_2008) <- df_2008[1,]
df_2008 <- df_2008[-1,]

df_2009 <- read_excel("Analysis Exercise.xls", 
                      sheet = "2009")
names(df_2009) <- df_2009[1,]
df_2009 <- df_2009[-1,]

df_peak_points <- read_excel("Analysis Exercise.xls", 
                      sheet = "Peak Points")
```

Clean the column names and add year variable.
```{r}
df_2000 <- df_2000 %>% clean_names() %>% mutate(year=2000)
df_2001 <- df_2001 %>% clean_names() %>% mutate(year=2001)
df_2002 <- df_2002 %>% clean_names() %>% mutate(year=2002)
df_2003 <- df_2003 %>% clean_names() %>% mutate(year=2003)
df_2004 <- df_2004 %>% clean_names() %>% mutate(year=2004)
df_2005 <- df_2005 %>% clean_names() %>% mutate(year=2005)
df_2006 <- df_2006 %>% clean_names() %>% mutate(year=2006)
df_2007 <- df_2007 %>% clean_names() %>% mutate(year=2007)
df_2008 <- df_2008 %>% clean_names() %>% mutate(year=2008)
df_2009 <- df_2009 %>% clean_names() %>% mutate(year=2009)
```

Merge all of data.
```{r}
df <- 
  bind_rows(df_2000, df_2001, df_2002, df_2003, df_2004, df_2005, df_2006, df_2007, df_2008, df_2009)
```

```{r}
data("stop_words")
```

